server:
  port: 8080

spring:
  config:
    import: values.properties

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

security:
  jwt:
    secret_key: ${JWT_SECRET_KEY}
    access_token_expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh_token_expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  aws:
    key_id: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    endpoint: ${AWS_ENDPOINT}
    bucket_name: ${AWS_BUCKET_NAME}
