name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: set up JDK 24
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Maven Checkstyle goal
        run: mvn checkstyle:check

      - name: test
        env:
          SPRING_PROFILES_ACTIVE: test
          POSTGRES_URL: jdbc:postgresql://localhost:5432/testdb
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          JWT_SECRET_KEY: 5fdbf80a06d57a9f315059c0f7ff523fa628ed603b70fae9d1258db7f36ae6ea93b61339
          JWT_ACCESS_TOKEN_EXPIRATION: 10000
          JWT_REFRESH_TOKEN_EXPIRATION: 1000000000000
          AWS_ACCESS_KEY_ID: RjkgfEI3fdb
          AWS_SECRET_ACCESS_KEY: 807a7ffb10b53fa6b5de42f0
          AWS_REGION: ru-central1-a
          AWS_ENDPOINT: https://storage.yandexcloud.net
          AWS_BUCKET_NAME: name
        run: mvn test

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload JAR on server
        run: |
          scp -o StrictHostKeyChecking=no target/*.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }}:${{ secrets.REMOTE_PATH }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            
            echo "Stopping and removing old container..."
            sudo docker stop cardCollection || true
            sudo docker rm cardCollection || true
            
            echo "Starting new container..."
            cd ${{ secrets.REMOTE_PATH }}
            sudo docker-compose up --build -d
            
            echo "Cleaning up old images..."
            docker image prune -f
